### ISSUE TITLE
[Feature Request] Adding support for pgsql 15

### ISSUE THREAD

**Issue by djoby** [ubc/barman-docker#10]
Hi there,

Since you r not using barman anymore, I doubt you will add this but there s no harm in asking.

Would it be possible to add support for postgresql 15 client in your dockerfile ?

Should I make a pr for this ?

Regards,

**Comment by xcompass** [comment]
A PR would be great. I can merge it. Thanks

Cheers
Pan

**Comment by djoby** [comment]
Sorry to post again in this closed issue (hope you ll see it anyway) but would it be possible to have a tag like "v3.3.1" or anything like that for the newly pushed image resulting of this merged pr ?

(Atm it s tagged with 'master' and 'sha-2b332b3' in docker hub)

**Comment by xcompass** [comment]
No worries. Thanks for the reminder. Pushed. Also updated barman to 3.4.1
