### ISSUE TITLE
[update-request] Barman updates available

### ISSUE THREAD

**Issue by hairmare** [ubc/barman-docker#3]
[Barman 2.17](https://github.com/EnterpriseDB/barman/releases/tag/release%2F2.17) was recently released. Have you considered updating this image? 

Since 2.10, the following things appear to have happened:
* barman migrated their repo to https://github.com/EnterpriseDB/barman/ (starting with 2.13)
* [`barman-cloud-wal-archive` and `barman-cloud-backup` where moved into the new `barman-cli-cloud` package](http://docs.pgbarman.org/release/2.13/#upgrading-from-barman-2.10)
* a few bugfixes have landed and there are some interesting new features like Azure blob support

FWIW their docs link to the 2.13 version so we might want to consider that "stable". If i look at pkgs.org it seems that most distros haven't made the switch to github hosted barman yet and are still using 2.12.

**Comment by xcompass** [comment]
Thanks for the info. The container has been updated in commit https://github.com/ubc/barman-docker/commit/8336923226b7125909c1f1d2a2497fcad5bba859

**Comment by hairmare** [comment]
Nice! Thanks for bumping all the way to 2.17 and also including the upgrade to bullseye 👍
