### ISSUE TITLE
Error "/tini: no such file or directory: unknown"

### ISSUE THREAD

**Issue by ghost** [ubc/barman-docker#5]
Hello, I'm using your image in Kubernetes and it gives me this error.

RunContainerError: failed to start container "c944dc805bc1b2c908ae069f70074eebf5b975c1574a4c012ea5973f8f9d6971": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/tini": stat /tini: no such file or directory: unknown

Do you know what it means? I had used your image before and no error was given. Can you help me?

**Comment by xcompass** [comment]
Hi @IamDopey, thanks for reporting the issue. It has been fixed. You can use latest or v2.17.2 tag.

**Comment by ghost** [comment]
Hello @xcompass, thanks a lot for solving the problem. :)
